version: "3.7"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-repo
    ports:
      - 8880:5000
    networks:
      - conditional-pipeline

networks:
  conditional-pipeline:
    driver: bridge
    name: conditional-pipeline
    external: true